services:
  app:
    build:
      context: src/main/java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5434/contas
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      sh -c "mvn clean package -DskipTests &&
             java -jar target/demo-0.0.1-SNAPSHOT.jar"
  db:
    image: bitnami/postgresql
    container_name: lyncas-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contas
    volumes:
      - .docker/volumes/postgres:/bitnami/postgresql
    ports:
      - "5434:5434"
    restart: always
